### ISSUE TITLE
关于数组的语法问题

### ISSUE THREAD

**Issue by MaureenChan** [vtmer/freshman#1]
我配置的时候数组那里还没改。而且我差不多改好的时候，出现了Unable to create the cache directory 。然后我在application的目录下mkdir cache。然后还是出这个错误。

**Comment by bcho** [comment]
`chmod 777 cache/`

**Comment by bcho** [comment]
话说你文不对题啊= =

**Comment by MaureenChan** [comment]
怎么了？

**Comment by MaureenChan** [comment]
噢，下次我会注意的！
