### ISSUE TITLE
ArticalController.php 修改

### ISSUE THREAD

**Issue by bcho** [vtmer/freshman#17]
根据 2014/4/3 的 code review，请对 [ArticalController.php](https://github.com/vtmer/freshman/blob/33552c80f20fe94d180bd388d1e88b958a8a99ce/backend/app/controllers/Backend/ArticalController.php) 做以下修改：
- [x] Artical 的命名
- [x] 数组变量的初始化
- [x] removeArtical 的逻辑
- [x] 代码风格

**Comment by bcho** [comment]
@Yannyezixin 你可以在后续的提交中进行修改。修改好了麻烦在本 issue 下回复并提供对应提交，我会进行检查。

**Comment by Yannyezixin** [comment]
修改以提交
https://github.com/Yannyezixin/freshman/commit/bc50a5feb96aaf25c126cfa2ca1433345b5a04b5

**Comment by bcho** [comment]
LGTM :+1:
