### ISSUE TITLE
不能创建新分类

### ISSUE THREAD

**Issue by bcho** [vtmer/freshman#21]
## 问题描述：

创建新分类的时候会显示

> xxx 已经存在，请选择其他名字
## 如何重现：

在 http://freshman-dev.youknowmymind.com/backend/catagory 里进行创建即可重现。

**Comment by Yannyezixin** [comment]
@bcho 我重行初始化了本地的数据库数据，发现没有这样的bug

> xxx 创建成功

请重新初始化数据库数据

**Comment by bcho** [comment]
你往你之前那个数据库文档里写上你怎么配置 mysql 的用户。

因为你本身配置里的 mysql 用户是 root，可能会有不同的。你试试配置一个普通用户看看效果。

2014-04-16 8:21 GMT+08:00 Yann notifications@github.com:
