### ISSUE TITLE
logout's bug after update

### ISSUE THREAD

**Issue by Yannyezixin** [vtmer/freshman#25]
# 问题描述

laravel版本升级之后用户退出会有错误提示信息
# 如何重现

同步之后进行用户登出即可重现

**Comment by bcho** [comment]
这个 bug 修好没有啊？

**Comment by Yannyezixin** [comment]
好啦。就是之前remember_token那个事

**Comment by bcho** [comment]
你下次应该在对应的 commit 里关联这个 issue

eg:

``` commit
Add `remember_token` support.

Fixed #25.
```

然后就可以在 #25 这个 issue 里看到对应的记录了。这样以后跟踪起来会比较方便。

当你确认修好了这个 bug 之后要关掉 issue。

**Comment by bcho** [comment]
Fixed via 4c609526dc257f6a295e9972ab5daa2744db84a9
