### ISSUE TITLE
后台管理文章列表功能增强

### ISSUE THREAD

**Issue by linkkingjay** [vtmer/freshman#30]
1. 给文章标题加上链接，点击后也可以进入编辑页面。
2. 可对各列进行排序，可以用 [tablesorter](http://tablesorter.com/) 。
3. “操作”那一列加一个“预览”的链接，用以跳转到这篇文章对应的前端页面（另外，在编辑文章的时候也应提供一个类似的链接）。

**Comment by Yannyezixin** [comment]
see #31

**Comment by Yannyezixin** [comment]
@linkkingjay I have change it again.see #31

**Comment by linkkingjay** [comment]
@Yannyezixin You made a syntax error again.
