### ISSUE TITLE
Tabsorter.js not found.

### ISSUE THREAD

**Issue by bcho** [vtmer/freshman#34]

**Comment by bcho** [comment]
http://freshman-dev.youknowmymind.com/static/js/tablesorter.js

Fixed.

cc @Yannyezixin

**Comment by bcho** [comment]
http://freshman-dev.youknowmymind.com/static/js/tablesorter.js

Fixed.

cc @yannzixin

**Comment by Yannyezixin** [comment]
I get it.
@bcho
