### ISSUE TITLE
列表页文章概要-字符截取

### ISSUE THREAD

**Issue by Yannyezixin** [vtmer/freshman#41]
字符截取：包括了html标签。html不完整。页面布局错乱。
重现：在后台发步新文章。开头须有排版样式
http://freshman-dev.youknowmymind.com/category/1

**Comment by bcho** [comment]
如果是 bug 最好提供一下具体是怎么样的情况（以及怎么复现）

**Comment by Yannyezixin** [comment]
fix it . see #43

**Comment by bcho** [comment]
@Yannyezixin 你这个修了么？

**Comment by Yannyezixin** [comment]
@bcho  我刚发pr了

**Comment by Yannyezixin** [comment]
see #43
