### ISSUE TITLE
Missing variable: $iconNumber

### ISSUE THREAD

**Issue by bcho** [vtmer/freshman#46]
## 如何重现

访问 http://freshman-dev.youknowmymind.com/ 即可

@Yannyezixin 尝试把赋值的操作放到 controller 里面。

Related to #38

**Comment by Yannyezixin** [comment]
<? $iconNumber = Config::get('...') ?>
这样写法不支持？

**Comment by bcho** [comment]
@Yannyezixin 不知道，你查查相关资料。但尽量避免在 view 里面进行赋值吧…… view 就应该只做显示而不是做一些逻辑处理啊。

**Comment by Yannyezixin** [comment]
```
     PHP 也允许使用短标记 <? 和 ?>，但不鼓励使用。只有通过激活 php.ini 中的 short_open_tag 配置         指令或者在编译 PHP 时使用了配置选项 --enable-short-tags 时才能使用短标记。
```

**Comment by bcho** [comment]
所以麻烦去掉这种用法。

在 2014年6月13日 下午1:28，Yann notifications@github.com写道：

**Comment by bcho** [comment]
Fixed via https://github.com/vtmer/freshman/commit/6d81bcbd7512a5ffe28f550f8ae610e6ee9fa757
