### ISSUE TITLE
文章内容css冲突

### ISSUE THREAD

**Issue by Yannyezixin** [vtmer/freshman#56]
see http://freshman-dev.youknowmymind.com/article/3/6
当文章内容html
`<ul> <span></span><ul>`时，style.css会改变其中css

**Comment by bcho** [comment]
没懂你的意思？明确点？

**Comment by Yannyezixin** [comment]
由于style.css中直接

``` css
ul span
{
}
```

所以当文章内容存在`<ul><span></span></ul>`就会有对其产生影响

**Comment by bcho** [comment]
明白

**Comment by Yannyezixin** [comment]
see #58
