### ISSUE TITLE
后台文章编辑器无法嵌入视频

### ISSUE THREAD

**Issue by linkkingjay** [vtmer/freshman#79]
在源码编辑模式下，插入类似

```
<embed src="http://player.youku.com/player.php/sid/XNjIwMjU0MjEy/v.swf" allowFullScreen="true" quality="high" width="480" height="400" align="middle" allowScriptAccess="always" type="application/x-shockwave-flash"></embed>
```

 代码无法保存。应该是被 CKEditor 过滤了，导致无法在页面嵌入视频。

参考：http://stackoverflow.com/questions/16975859/ckeditor-doesn%C2%B4t-read-media-embed-code

**Comment by bcho** [comment]
Fixed via ae2f307

@linkkingjay Please review this change. If you feel ok, merge to master branch. Thanks!

**Comment by linkkingjay** [comment]
@bcho @Yannyezixin  OK
